/**
 * Permission IDs mapped from `ids_permission.txt`.
 *
 * These IDs are sent to backend when updating Employee Privileges.
 */
export const PERMISSION_ID_BY_TAG = Object.freeze({
  // Employee
  EMPLOYEE_FULL_ACCESS: 354,
  EMPLOYEE_READ_ONLY: 297,
  EMPLOYEE_NO_ACCESS: 355,

  // Department
  DEPARTMENT_FULL_ACCESS: 356,
  DEPARTMENT_READ_ONLY: 357,
  DEPARTMENT_NO_ACCESS: 308,

  // HR Policies
  HR_POLICIES_FULL_ACCESS: 309,
  HR_POLICIES_READ_ONLY: 310,
  HR_POLICIES_NO_ACCESS: 311,

  // Payroll
  PAYROLL_SALARY_TEMPLATES_FULL_ACCESS: 312,
  PAYROLL_SALARY_TEMPLATES_READ_ONLY: 313,
  PAYROLL_SALARY_TEMPLATES_NO_ACCESS: 314,

  PAYROLL_EMPLOYEES_SALARY_FULL_ACCESS: 315,
  PAYROLL_EMPLOYEES_SALARY_READ_ONLY: 316,
  PAYROLL_EMPLOYEES_SALARY_NO_ACCESS: 317,

  PAYROLL_PAYSLIPS_MANAGEMENT_FULL_ACCESS: 318,
  PAYROLL_PAYSLIPS_MANAGEMENT_READ_ONLY: 319,
  PAYROLL_PAYSLIPS_MANAGEMENT_NO_ACCESS: 320,

  PAYROLL_REPORTS_EXPORT_FULL_ACCESS: 321,
  PAYROLL_REPORTS_EXPORT_READ_ONLY: 322,
  PAYROLL_REPORTS_EXPORT_NO_ACCESS: 323,

  // Notices
  NOTICES_FULL_ACCESS: 324,
  NOTICES_READ_ONLY: 325,
  NOTICES_NO_ACCESS: 326,

  // Tasks
  TASKS_FULL_ACCESS: 327,
  TASKS_READ_ONLY: 328,
  TASKS_NO_ACCESS: 329,

  // Attendance
  ATTENDANCE_DATA_FULL_ACCESS: 330,
  ATTENDANCE_DATA_READ_ONLY: 331,
  ATTENDANCE_DATA_NO_ACCESS: 332,

  ATTENDANCE_EXPORT_FULL_ACCESS: 333,
  ATTENDANCE_EXPORT_READ_ONLY: 334,
  ATTENDANCE_EXPORT_NO_ACCESS: 335,

  BRANCH_WISE_ATTENDANCE_FULL_ACCESS: 336,
  BRANCH_WISE_ATTENDANCE_READ_ONLY: 337,
  BRANCH_WISE_ATTENDANCE_NO_ACCESS: 338,

  ATTENDANCE_RAW_LOGS_FULL_ACCESS: 339,
  ATTENDANCE_RAW_LOGS_READ_ONLY: 340,
  ATTENDANCE_RAW_LOGS_NO_ACCESS: 341,

  // Shift planner
  SHIFT_PLANNER_FULL_ACCESS: 342,
  SHIFT_PLANNER_READ_ONLY: 343,
  SHIFT_PLANNER_NO_ACCESS: 344,

  // Applications
  APPLICATIONS_FULL_ACCESS: 345,
  APPLICATIONS_READ_ONLY: 346,
  APPLICATIONS_NO_ACCESS: 347,

  // Leave planner
  LEAVE_PLANNER_FULL_ACCESS: 348,
  LEAVE_PLANNER_READ_ONLY: 349,
  LEAVE_PLANNER_NO_ACCESS: 350,

  // Forms & Approval
  FORMSANDAPPROVE_FULL_ACCESS: 351,
  FORMSANDAPPROVE_READ_ONLY: 352,
  FORMSANDAPPROVE_NO_ACCESS: 353,

  // Hire 2.0 (note: backend tag uses underscore in ids file)
  HIRE2_0_FULL_ACCESS: 358,
  HIRE2_0_READ_ONLY: 359,
  HIRE2_0_NO_ACCESS: 360,
});

